/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distNorteInterface;

/**
 *
 * @author fmollea
 */
public class FrameMain extends javax.swing.JFrame {

    /**
     * Creates new form FrameMain
     */
    public FrameMain() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ButtonClient = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ButtonProvider = new javax.swing.JButton();
        ButtonProduct = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        LabelTittle = new javax.swing.JLabel();
        LabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distNorteInterface/images/client.jpg"))); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(290, 266));
        jButton1.setMinimumSize(new java.awt.Dimension(290, 266));
        jButton1.setPreferredSize(new java.awt.Dimension(125, 125));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        ButtonClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distNorteInterface/images/client.jpg"))); // NOI18N
        ButtonClient.setMaximumSize(new java.awt.Dimension(290, 266));
        ButtonClient.setMinimumSize(new java.awt.Dimension(290, 266));
        ButtonClient.setPreferredSize(new java.awt.Dimension(125, 125));
        ButtonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClientActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distNorteInterface/images/client.jpg"))); // NOI18N
        jButton3.setMaximumSize(new java.awt.Dimension(290, 266));
        jButton3.setMinimumSize(new java.awt.Dimension(290, 266));
        jButton3.setPreferredSize(new java.awt.Dimension(125, 125));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        ButtonProvider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distNorteInterface/images/provider.jpg"))); // NOI18N
        ButtonProvider.setMaximumSize(new java.awt.Dimension(290, 266));
        ButtonProvider.setMinimumSize(new java.awt.Dimension(290, 266));
        ButtonProvider.setPreferredSize(new java.awt.Dimension(125, 125));
        ButtonProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProviderActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonProvider, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        ButtonProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distNorteInterface/images/product.jpg"))); // NOI18N
        ButtonProduct.setMaximumSize(new java.awt.Dimension(290, 266));
        ButtonProduct.setMinimumSize(new java.awt.Dimension(290, 266));
        ButtonProduct.setPreferredSize(new java.awt.Dimension(125, 125));
        ButtonProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProductActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distNorteInterface/images/client.jpg"))); // NOI18N
        jButton6.setMaximumSize(new java.awt.Dimension(290, 266));
        jButton6.setMinimumSize(new java.awt.Dimension(290, 266));
        jButton6.setPreferredSize(new java.awt.Dimension(125, 125));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        LabelTittle.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelTittle.setForeground(new java.awt.Color(255, 255, 255));
        LabelTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTittle.setText("Gestor de Negocios");
        LabelTittle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LabelTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 200, -1));

        LabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distNorteInterface/images/background.jpg"))); // NOI18N
        LabelBackground.setText("jLabel1");
        getContentPane().add(LabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 532, 435));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonClientActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ButtonProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProviderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonProviderActionPerformed

    private void ButtonProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonProductActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClient;
    private javax.swing.JButton ButtonProduct;
    private javax.swing.JButton ButtonProvider;
    private javax.swing.JLabel LabelBackground;
    private javax.swing.JLabel LabelTittle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    // End of variables declaration//GEN-END:variables
}
