/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distNorteInterface;

import com.sun.glass.events.KeyEvent;

/**
 *
 * @author fmollea
 */
public class FrameMain extends javax.swing.JFrame {

    /**
     * Creates new form FrameMain
     */
    public FrameMain() {
        initComponents();
        //The frame is center
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonSearch = new javax.swing.JButton();
        ButtonClient = new javax.swing.JButton();
        ButtonInvoice = new javax.swing.JButton();
        ButtonProvider = new javax.swing.JButton();
        ButtonProduct = new javax.swing.JButton();
        ButtonBuy = new javax.swing.JButton();
        LabelTittle = new javax.swing.JLabel();
        ExitButtin = new javax.swing.JButton();
        LabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distNorteInterface/images/search.jpg"))); // NOI18N
        ButtonSearch.setMaximumSize(new java.awt.Dimension(290, 266));
        ButtonSearch.setMinimumSize(new java.awt.Dimension(290, 266));
        ButtonSearch.setPreferredSize(new java.awt.Dimension(125, 125));
        ButtonSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonSearchMouseClicked(evt);
            }
        });
        ButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSearchActionPerformed(evt);
            }
        });
        ButtonSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonSearchKeyPressed(evt);
            }
        });
        getContentPane().add(ButtonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        ButtonClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distNorteInterface/images/client.jpg"))); // NOI18N
        ButtonClient.setMaximumSize(new java.awt.Dimension(290, 266));
        ButtonClient.setMinimumSize(new java.awt.Dimension(290, 266));
        ButtonClient.setPreferredSize(new java.awt.Dimension(125, 125));
        ButtonClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonClientMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonClientMouseClicked(evt);
            }
        });
        ButtonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClientActionPerformed(evt);
            }
        });
        ButtonClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonClientKeyPressed(evt);
            }
        });
        getContentPane().add(ButtonClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        ButtonInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distNorteInterface/images/invoice.jpg"))); // NOI18N
        ButtonInvoice.setMaximumSize(new java.awt.Dimension(290, 266));
        ButtonInvoice.setMinimumSize(new java.awt.Dimension(290, 266));
        ButtonInvoice.setPreferredSize(new java.awt.Dimension(125, 125));
        ButtonInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonInvoiceMouseClicked(evt);
            }
        });
        ButtonInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInvoiceActionPerformed(evt);
            }
        });
        ButtonInvoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonInvoiceKeyPressed(evt);
            }
        });
        getContentPane().add(ButtonInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        ButtonProvider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distNorteInterface/images/provider.jpg"))); // NOI18N
        ButtonProvider.setMaximumSize(new java.awt.Dimension(290, 266));
        ButtonProvider.setMinimumSize(new java.awt.Dimension(290, 266));
        ButtonProvider.setPreferredSize(new java.awt.Dimension(125, 125));
        ButtonProvider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonProviderMouseClicked(evt);
            }
        });
        ButtonProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProviderActionPerformed(evt);
            }
        });
        ButtonProvider.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonProviderKeyPressed(evt);
            }
        });
        getContentPane().add(ButtonProvider, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        ButtonProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distNorteInterface/images/product.jpg"))); // NOI18N
        ButtonProduct.setMaximumSize(new java.awt.Dimension(290, 266));
        ButtonProduct.setMinimumSize(new java.awt.Dimension(290, 266));
        ButtonProduct.setPreferredSize(new java.awt.Dimension(125, 125));
        ButtonProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonProductMouseClicked(evt);
            }
        });
        ButtonProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProductActionPerformed(evt);
            }
        });
        ButtonProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonProductKeyPressed(evt);
            }
        });
        getContentPane().add(ButtonProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        ButtonBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distNorteInterface/images/buy.jpg"))); // NOI18N
        ButtonBuy.setMaximumSize(new java.awt.Dimension(290, 266));
        ButtonBuy.setMinimumSize(new java.awt.Dimension(290, 266));
        ButtonBuy.setPreferredSize(new java.awt.Dimension(125, 125));
        ButtonBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonBuyMouseClicked(evt);
            }
        });
        ButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuyActionPerformed(evt);
            }
        });
        ButtonBuy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonBuyKeyPressed(evt);
            }
        });
        getContentPane().add(ButtonBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        LabelTittle.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LabelTittle.setForeground(new java.awt.Color(255, 255, 255));
        LabelTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTittle.setText("Gestor de Negocios");
        LabelTittle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(LabelTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 200, -1));

        ExitButtin.setBackground(new java.awt.Color(102, 0, 0));
        ExitButtin.setForeground(new java.awt.Color(204, 204, 204));
        ExitButtin.setText("X");
        ExitButtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtinActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, -1));

        LabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/distNorteInterface/images/background.jpg"))); // NOI18N
        LabelBackground.setText("jLabel1");
        getContentPane().add(LabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 532, 435));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSearchActionPerformed

    private void ButtonClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonClientActionPerformed

    private void ButtonInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonInvoiceActionPerformed

    private void ButtonProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProviderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonProviderActionPerformed

    private void ButtonProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonProductActionPerformed

    private void ButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBuyActionPerformed
    //create clientFrame
    private void ButtonClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonClientMouseClicked
        FrameClient frameClient = new FrameClient();
        frameClient.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonClientMouseClicked

    private void ButtonClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonClientMousePressed
        
    }//GEN-LAST:event_ButtonClientMousePressed

    private void ButtonClientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonClientKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            FrameClient frameClient = new FrameClient();
            frameClient.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_ButtonClientKeyPressed

    private void ExitButtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtinActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtinActionPerformed

    private void ButtonProviderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonProviderMouseClicked
        FrameProvider frameProvider = new FrameProvider();
        frameProvider.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonProviderMouseClicked

    private void ButtonProviderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonProviderKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            FrameProvider frameProvider = new FrameProvider();
            frameProvider.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_ButtonProviderKeyPressed

    private void ButtonProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonProductMouseClicked
        FrameProduct frameProduct = new FrameProduct();
        frameProduct.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonProductMouseClicked

    private void ButtonProductKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonProductKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            FrameProduct frameProduct = new FrameProduct();
            frameProduct.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_ButtonProductKeyPressed

    private void ButtonInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonInvoiceMouseClicked
        FrameInvoice frameInvoice = new FrameInvoice();
        frameInvoice.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonInvoiceMouseClicked

    private void ButtonInvoiceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonInvoiceKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){    
            FrameInvoice frameInvoice = new FrameInvoice();
            frameInvoice.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_ButtonInvoiceKeyPressed

    private void ButtonBuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBuyMouseClicked
        FrameBuy frameBuy = new FrameBuy();
        frameBuy.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonBuyMouseClicked

    private void ButtonBuyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonBuyKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){    
            FrameBuy frameBuy = new FrameBuy();
            frameBuy.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_ButtonBuyKeyPressed

    private void ButtonSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSearchMouseClicked
        FrameSearch frameSearch = new FrameSearch();
        frameSearch.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonSearchMouseClicked

    private void ButtonSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonSearchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){      
            FrameSearch frameSearch = new FrameSearch();
            frameSearch.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_ButtonSearchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuy;
    private javax.swing.JButton ButtonClient;
    private javax.swing.JButton ButtonInvoice;
    private javax.swing.JButton ButtonProduct;
    private javax.swing.JButton ButtonProvider;
    private javax.swing.JButton ButtonSearch;
    private javax.swing.JButton ExitButtin;
    private javax.swing.JLabel LabelBackground;
    private javax.swing.JLabel LabelTittle;
    // End of variables declaration//GEN-END:variables
}
